  
services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    
  rydio_backend:
    container_name: rydio_backend
    build:
      context : ./
      dockerfile: ./Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - rydio_network
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - rydio_network
    
networks:
  rydio_network:
    name: rydio_network
    driver: bridge
