version: "3.9"

services:
  rydio-backend:
    image: REPLACE_WITH_IMAGE_TAG
    container_name: rydio-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "3003:3003"
    networks:
      - rydio_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rydio_network

  prom-server:
    image: prom/prometheus
    container_name: prom-server
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    networks:
      - rydio_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rydio_network
    depends_on:
      - prom-server

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./rydio.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rydio_network
    depends_on:
      - rydio-backend

volumes:
  certbot_data:

networks:
  rydio_network:
    driver: bridge
