
services:
  backend:
    image: REPLACE_WITH_IMAGE_TAG
    container_name: rydio-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "3003:3003"

    redis:
     image: redis:7
     container_name: redis
     restart: always
     ports:
       - "6379:6379"
     networks:
       - rydio_network

  prom-server:
    image: prom/prometheus
    container_name: prom-server
    restart: always
    ports:
      - "9090:9090"
    volumes:
      # go up one level to find prometheus/
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./rydio.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rydio_network
    depends_on:
      - rydio-backend
